version: "3.7"
services:
  app:
    build:
      args:
        user: user
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: app
    container_name: app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_DATABASE=interaction_gifs
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    security_opt:
      - seccomp:unconfined

  nginx:
    build:
      context: ./
      dockerfile: ./.docker/nginx/Dockerfile
    volumes:
      - ./:/var/www:cached
    ports:
      - "80:80"
    depends_on:
      - app

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql:mysql
    ports:
      - 8081:80
    environment:
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      PMA_HOST: mysql

volumes:
  mysql-data:
